name: Update README

on:
  push:
    branches:
      - main # Adjust the branch name if needed

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run update-readme.sh
        run: ../update-readme.sh
